create table public.votes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  email text not null check (char_length(btrim(email)) between 3 and 320),
  shirt_number smallint not null check (shirt_number between 1 and 7),
  created_at timestamptz not null default now(),
  constraint votes_user_id_unique unique (user_id)
);

create unique index votes_email_unique
  on public.votes (lower(trim(email)));

alter table public.votes enable row level security;

revoke all on table public.votes from anon, authenticated, public;
grant insert on table public.votes to authenticated;
grant usage on sequence public.votes_id_seq to authenticated;

create policy "authenticated users can insert their own vote"
  on public.votes
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and email = (auth.jwt() ->> 'email')
  );

create or replace function public.vote_totals()
returns table (shirt_number integer, total bigint)
language sql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
  select
    options.shirt_number::integer,
    count(votes.id)::bigint as total
  from generate_series(1, 7) as options(shirt_number)
  left join public.votes as votes
    on votes.shirt_number = options.shirt_number
  group by options.shirt_number
  order by options.shirt_number;
$$;

revoke all on function public.vote_totals() from public;
grant execute on function public.vote_totals() to anon, authenticated;
