create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  email text not null check (char_length(btrim(email)) between 3 and 320),
  shirt_number smallint not null check (shirt_number between 1 and 7),
  created_at timestamptz not null default now()
);

create unique index if not exists votes_email_unique
  on public.votes (lower(trim(email)));

alter table public.votes enable row level security;

-- Permite inserção pública (qualquer pessoa pode votar uma vez por e-mail)
create policy "public can insert votes"
  on public.votes
  for insert
  to anon
  with check (true);

-- Bloqueia leitura, atualização e exclusão de linhas
revoke select, update, delete on table public.votes from anon, authenticated, public;

-- RPC para consultar totais (segura, sem expor dados pessoais)
create or replace function public.vote_totals()
returns table (shirt_number integer, total bigint)
language sql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
  select
    options.shirt_number::integer,
    count(votes.id)::bigint as total
  from generate_series(1, 7) as options(shirt_number)
  left join public.votes as votes
    on votes.shirt_number = options.shirt_number
  group by options.shirt_number
  order by options.shirt_number;
$$;

revoke all on function public.vote_totals() from public;
grant execute on function public.vote_totals() to anon, authenticated;

-- RPC para listar votos (nome + camisa) — dados não secretos
create or replace function public.vote_list()
returns table (name text, shirt_number integer)
language sql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
  select
    votes.name,
    votes.shirt_number::integer
  from public.votes as votes
  order by votes.created_at;
$$;

revoke all on function public.vote_list() from public;
grant execute on function public.vote_list() to anon, authenticated;
